### ISSUE TITLE
请问paper中的General Domain Dataset在哪里？在data文件夹下面没看到

### ISSUE THREAD

**Issue by xukefaker** [Alibaba-NLP/Multi-CPR#5]
谢谢！

**Comment by dingkun-ldk** [comment]
general domain的数据是从dureader数据转换得到的, dureader数据集可以参考 https://ai.baidu.com/broad/leaderboard?dataset=dureader

**Comment by xukefaker** [comment]
> general domain的数据是从dureader数据转换得到的, dureader数据集可以参考 https://ai.baidu.com/broad/leaderboard?dataset=dureader

那请问你们有相应的转换工具吗？
