### ISSUE TITLE
领域预训练模型 

### ISSUE THREAD

**Issue by xxllp** [Alibaba-NLP/Multi-CPR#9]
我看论文有对比这块的效果 但是代码里面没看到提供对应的预训练模型

**Comment by dingkun-ldk** [comment]
你好, 这块的代码和模型没有提供，利用领域数据对BERT模型进一步预训练可以直接参考transformers提供的LM预训练代码 https://huggingface.co/transformers/v3.0.2/model_doc/bert.html
